server:
  port: 8880

spring:
  profiles:
    active: @profiles.active@

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  checkConfigLocation: false
  configuration:
    mapUnderscoreToCamelCase: true
    autoMappingBehavior: FULL
    autoMappingUnknownColumnBehavior: NONE
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapperPackage: com.juege.**.mapper
  mapperLocations: classpath*:mapper/**/*Mapper*.xml
  typeAliasesPackage: com.juege.**.domain
  global-config:
    dbConfig:
      idType: ASSIGN_ID

test:
  hello: Hello4